name: ci
run-name: ${{ github.actor }} is running CI 🚀

on:
  push:
    branches:
      - develop

jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      node_ver: ${{ steps.node_ver.outputs.node_ver }}
      pnpm_ver: ${{ steps.pnpm_ver.outputs.pnpm_ver }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup PNPM
        uses: pnpm/setup@v2
      - id: node_ver
        run: echo "node_ver=$(node --version)" >> $GITHUB_OUTPUT
      - id: pnpm_ver
        run: echo "pnpm_ver=$(pnpm --version)" >> $GITHUB_OUTPUT

  run-tests:
    needs: versions
    uses: ./.github/workflows/run-tests.yml
    with:
      node_ver: ${{ needs.versions.outputs.node_ver }}
      pnpm_ver: ${{ needs.versions.outputs.pnpm_ver }}

