name: ci
run-name: ${{ github.actor }} is running CI 🚀

on:
  push:
    branches:
      - develop

jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      node_ver: ${{ steps.vars.outputs.node_ver }}
      pnpm_ver: ${{ steps.vars.outputs.pnpm_ver }}
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
      - run: node --version
      - run: pnpm --version

  run-tests:
    needs: versions
    uses: ./.github/workflows/run-tests.yml
    with:
      node_ver: ${{ needs.versions.outputs.node_ver }}
      pnpm_ver: ${{ needs.versions.outputs.pnpm_ver }}

