name: ci
run-name: ${{ github.actor }} is running CI 🚀

on:
  push:
    branches:
      - develop

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml
  generate-docs:
    needs: run-tests
    uses: ./.github/workflows/generate-docs.yml
    permissions:
      contents: read
      pages: write
      id-token: write

