name: generate-docs
run-name: ${{ github.actor }} is generating documentation 🚀

on:
  workflow_call:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install pnpm + Node.js
        uses: pnpm/setup@v2
      - name: Build documentation
        run: pnpm build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
