name: run-tests
run-name: ${{ github.actor }} is running tests 🧪

on:
  workflow_call:
    inputs:
      node_ver:
        required: true
        type: string
      pnpm_ver:
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input name to STDOUT
        run: echo The Node version is ${{ inputs.node_ver }}
      - name: Print the input name to STDOUT
        run: echo The pnpm version is ${{ inputs.pnpm_ver }}
